obj-$(CONFIG_VIRTUAL_USB_FW)		+= dummy.o
obj-$(CONFIG_VIRTUAL_UDC_AND_HCD)	+= dummy_hcd2.o

obj-$(CONFIG_VIRTUAL_USB_HCD)		+= dummy_hcd.o
obj-$(CONFIG_VIRTUAL_USB_UDC)		+= dummy_udc.o
obj-$(CONFIG_VIRTUAL_USB_DEVICES)	+= devices.o
