obj-$(CONFIG_VIRTUAL_USB_FW)		+= dummy.o

obj-$(CONFIG_VIRTUAL_USB_UDC_DRV)		+= virtual_udc_drv.o
obj-$(CONFIG_VIRTUAL_USB_UDC_REG)		+= virtual_udc_create.o
obj-$(CONFIG_VIRTUAL_USB_HCD_DRV)		+= virtual_hcd_drv.o
obj-$(CONFIG_VIRTUAL_USB_HCD_REG)		+= virtual_hcd_create.o

obj-$(CONFIG_VIRTUAL_USB_CONFIGFS)	+= libvirtusb.o
libvirtusb-y				:= configfs.o
